### ISSUE TITLE
2 minibosses listed in the bosses checklist.

### ISSUE THREAD

**Issue by GifanTheWoodElf** [Gobluebro/Elden-Ring-Checklist#101]
Greyoll in Dragonbarrow, and the Tibia mariner on the Mountaintops of the giants are just non-respawning enemies/minibosses, but they don't have a boss health bar.

**Comment by Gobluebro** [comment]
Bosses list comes from here https://eldenring.wiki.fextralife.com/Bosses. It is true that both of these bosses do not have health bars, but until they get taken off these lists I don't feel comfortable removing them. I think Greyoll especially is a boss many people specifically remember in their play through, and will probably come to the issues section to have it added back if it were removed.

**Comment by GifanTheWoodElf** [comment]
I mean the game literally doesn't consider it a boss. So IDK why would the opinion of whoever edited the wiki matter, but you do you I guess. (Although I did just edit the wiki page to fix it, so if the wiki is the ultimate guide of what's right and wrong it's currently indeed accurate)

**Comment by Gobluebro** [comment]
I get that you feel strongly about this topic, though there is a better way to have a discussion on this. 

In the past I have ruled on bosses who have no boss bars won't be counted #83 

And I do see the point. The game likes to reuse assets whenever they can, crucible knight is a great example 
![image](https://github.com/user-attachments/assets/635a6e13-8be7-45cd-a9af-387c4377e666)
Obviously no one would consider stormveil castle crucible knight as a boss but just a strong enemy.

I think it mostly comes down to more times an enemy asset is used the more the novelty of that enemy wears off. And I think the tree avatars and tibia mariner also fall into that category. There is only one Elder Dragon Greyoll though and I think the impact/novelty of this boss still holds pretty strongly for most players. e.g. https://screenrant.com/elden-ring-caelid-white-dragon-greyoll-dragonbarrow-farming/

**Comment by GifanTheWoodElf** [comment]
Well I mean yeah, Greyoll is an important/interesting enemy, and sure she's a novelty enemy with the way you kill her, but I don't see what does that have to do with the boss status. Like an enemy being a boss is just the existence of a boss health bar (and perhaps "*enemy* felled" pop up), saying she's not a boss isn't meant to mean she's unimportant, merely that she mechanically, gameplay wise she wouldn't be considered a boss.

**Comment by Gobluebro** [comment]
And I can't argue that this enemy specifically fits the bill perfect for what defines a boss, but the goal of the website isn't to be super strict in all aspects. I don't need to create a separate list of "interesting enemies" when there is less than a handful and I already have this great long list of bosses. 

I'm just adding the content I believe players would want to see if they wanted to make sure they experienced everything the game has to offer. The end user should be someone who wants to make sure they check off everything they have cleared so far to ensure that they didn't miss out on anything important. That's why some quest lines also have bias towards the better endings instead of the ones that cut off leaving you feel bad of the choices you made by following the website..
