### ISSUE TITLE
Erdtree Avatar in Caelid

### ISSUE THREAD

**Issue by 13xforever** [Gobluebro/Elden-Ring-Checklist#14]
I've done Caelid and I haven't met Erdtree Avatar listed in the Bosses section of the checklist. It is also [not mentioned](https://eldenring.wiki.fextralife.com/Erdtree+Avatar) in the wiki for this area.

It might be that this boss was swapped for a second Putrid Avatar instead (issue #9)

**Comment by 13xforever** [comment]
On a related note, I think Isolated Divine Tower in Greyoll's Dragonbarrow was split in two: Divine Tower of Caelid: Center and Basement (wiki also has [11 locations listed](https://eldenring.wiki.fextralife.com/Dragonbarrow) plus Deep Siofra Well, which should be in Caelid)

**Comment by Gobluebro** [comment]
So talking about this erdtree avatar issue specially:

This was once called Erdtree avatar but has since been renamed.
Wiki location still shows that here
![image](https://user-images.githubusercontent.com/14102413/164116073-45e93ac5-4657-4731-9e20-102b10d8da0f.png)

Here is a youtube video with the previous name:
https://www.youtube.com/watch?v=7RqpYe852-A

Here is my current in game screenshot of the new name:
![image](https://user-images.githubusercontent.com/14102413/164116126-c50ccf35-8597-43a6-b029-0a2ce5abee43.png)

So I will update that

**Comment by Gobluebro** [comment]
> On a related note, I think Isolated Divine Tower in Greyoll's Dragonbarrow was split in two: Divine Tower of Caelid: Center and Basement (wiki also has [11 locations listed](https://eldenring.wiki.fextralife.com/Dragonbarrow) plus Deep Siofra Well, which should be in Caelid)

I don't believe this is related to this issue. 

Isolated Divine Tower grace is still in the game https://eldenring.wiki.fextralife.com/Isolated+Divine+Tower 

It is not really in caelid nor other places it's just in the middle of the map. Is it really the best to put it in Caelid graces? Probably not. I don't really have any good place to put it and got this data from the wiki itself. You can find the started discussion on which region is the best to place something in this issue here https://github.com/Gobluebro/Elden-Ring-Checklist/issues/8

**Comment by Gobluebro** [comment]
Removed Erdtree avatar [in this commit.](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/efa5bda8fd78833903f58e7f9b9ef7bd0292931f)

The correct name was already in caelid bosses listed as `Putrid Avatar (West Caelid)`
