### ISSUE TITLE
Search Functionality 

### ISSUE THREAD

**Issue by JustAnOkapi** [Gobluebro/Elden-Ring-Checklist#3]
- Make a button to open all dropdown boxes at once, so you can ctrl-f browser search
- or have an integrated search

**Comment by Gobluebro** [comment]
> Make a button to open all dropdown boxes at once, so you can ctrl-f browser search

I think this is reasonable. 

> or have an integrated search

I'm not sure how this might work with quests since they have different wording than every other list. 


In the mean time, [I have added this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/70b951fba5ba676d0ae998fb6184cd38cf4a1b3d) to change the default from all closed to all open so you may ctrl+f browser search. I will get to the button later.

May I ask what you generally are searching for when using this website?

**Comment by JustAnOkapi** [comment]
Mainly it was searching for bosses and graces by their name.

**Comment by Gobluebro** [comment]
Thanks for the feedback.

The graces are listed in the order the game presents them if that helps as well. So you can see immediately if you are missing any.

**Comment by Gobluebro** [comment]
Added the open all / close all button [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/9cc0bbdef1d30b85d9688d657d5e5e6f411b47c3)

There is a bug currently where if you close all then open them all manually one by one it will still try to open all when clicking this new button again.

I'll be working on a fix for that but I'm going to close this request since it has been completed.

**Comment by Gobluebro** [comment]
Fixed that bug [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/20a7262fdeabbbaf1c338a3c4eb43c67c1edb1c5)
