### ISSUE TITLE
Alphabetical sort for NPC names

### ISSUE THREAD

**Issue by Tom-Smith-95** [Gobluebro/Elden-Ring-Checklist#33]
There are quite a few NPCs, and finding their dropdowns in the quest tab can be a bit annoying since they do not appear to be sorted in any way. Please sort the NPCs according to their names alphabetically.

**Comment by Gobluebro** [comment]
Hey there

The current sort order of quests is based on the progression of the game.  Due to the open world of the game, you may not encounter them in this exact order but generally they will be around similar level range. 

(If they are not, feel free to let me know the order they should be in and why)

I could see maybe doing like a sort dropdown or something but if there is only going to be 2 sort options it doesn't seem worth it.

For most of this project, users have used CTRL + F to find what they are looking for since things like graces are an even longer list than quests. 

I think it might be time to make an official search bar for this issue. Will put on the list of todos

**Comment by Tom-Smith-95** [comment]
As you said, given that this is an open world game, I don't think there is such a thing as progression order. In these cases I think the best would be simply having an alphabetical sort.
For example, right now I don't think it makes sense to have Seluvis so far from Ranni, and so close to the bottom of the list, past the Dung Eater. You could pick examples like this all day, or argue that they should be sorted according to the overall [area scaling](https://docs.google.com/spreadsheets/d/1Cj1ZT2VH-rjWddqDSY0zTvNZfolZlXAHqhrdnTQe7hQ/edit) they are first found in, but at the end of the day I think the best way to sort them is alphabetically, especially if you use the quest checklists on your phone. Ctrl+F on a phone is a pain. And using a search bar is also less convenient than simply scrolling to a NPCs name and quickly tapping the options you want checked/unchecked. It's faster even than using a mouse.

**Comment by Gobluebro** [comment]
Hmm... What about how they are currently named? Since these are quests not just one NPC what if someone is looking for "blah blah" ending, do you sort by ending or NPC or what about the case for multiple NPCs in one quest line?

like this
![image](https://user-images.githubusercontent.com/14102413/221325522-416d1dca-4b6a-40ec-bcf4-54507f9185f4.png)

**Comment by Tom-Smith-95** [comment]
I think the way they are written now is fine. The first name on the list is the NPC that starts the quest and the others are NPCs that you find later on tied to the quest. I'd just sort them alphabetically as they are now.

If you want to emphasize the ending instead of the NPC that starts the quest, you could do something like this to keep all endings together once sorted alphabetically:

- Ending: Age of Stars (Ranni)
- Ending: Age of Order (Corhyn, Goldmask)
- Ending: Blessing of Despair (Dung Eater)
- Ending: Lord of the Frenzied Flame (Irina, Edgar, Hyetta)

I think either way is fine. This game does not have quest names, which is annoying, so putting the name of the NPC first makes sense. Writing the ending first and then the NPCs involved later would also make sense since endings are kind of a big deal and players might want to get a certain ending. Personally, I don't have a preference.

**Comment by Gobluebro** [comment]
Sorted by name on commit a345384

**Comment by Gobluebro** [comment]
used ending naming scheme on dd4300b

hope this helps
