### ISSUE TITLE
Boc quest

### ISSUE THREAD

**Issue by Tom-Smith-95** [Gobluebro/Elden-Ring-Checklist#38]
2 new lines need to be added:
- Purchase a piece of armor that can be altered from Enia at the Roundtable Hold.
- Select the "I'm sorry..." dialogue option.

They need to be added before this one:
- Give the Gold Sewing Needle to Boc at any of the previous places you talked to him at.

EDIT:
I've just realized this option exists: "Buy an armor piece from Finger Reader Enia at the Roundtable Hold."
I checked it after buying some gloves or something like that, not realizing that the armor piece must be able to be altered. Maybe this line needs to be changed to mention that the armor piece should be alterable, just like the first line I suggest adding.

**Comment by Gobluebro** [comment]
I'm not sure where this is at 
> Select the "I'm sorry..." dialogue option.

Do you have anymore detail about where this dialogue takes place?

From what I've read, most of this questline isn't exactly required. I feels more like it's just here so that you can get free clothes alternations and where to find him in game. I've read that to get the good ending, all you need to do is use the "you're beautiful" prattling pate after step 2 and you will insure the good ending.

**Comment by Gobluebro** [comment]
Changing the line to read

> Buy an alterable boss armor piece from Finger Reader Enia at the Roundtable Hold.

Adding warning to warn players about giving him a larval tear.

> Talk to Boc but do not give him the larval tear unless you are going for the bad ending.

**Comment by Gobluebro** [comment]
Changes added in 559a6cc
