### ISSUE TITLE
Option to have Checked Items dissappear

### ISSUE THREAD

**Issue by kingkhezu** [Gobluebro/Elden-Ring-Checklist#5]
Hello my friend, first of all thanks for this amazing list, I've used something like this to complete DS3 back in the day and I was waiting for a decent checklist since release.
Now one feature that I would love to see is having the ability to hide checked items. Just makes the process of 100%ing everything a bit easier to organize and IMO its a nice feeling seeing the list shrink 😛 

Hopefully thats not too hard to implement. 
Have a nice day!

**Comment by Gobluebro** [comment]
Hello

I'm not sure what you mean by hiding a checked item. Do you have a website that did this previously that you can show me what you mean? Any further explanation you might be able to add as well would be helpful.

Thanks

**Comment by JustAnOkapi** [comment]
> Do you have a website that did this previously that you can show me what you mean?

[http://zkjellberg.github.io/dark-souls-3-cheat-sheet/#Cemetery_of_Ash](http://zkjellberg.github.io/dark-souls-3-cheat-sheet/#Cemetery_of_Ash) 

> Any further explanation you might be able to add as well would be helpful.

A button that will make any item that is checked disappear.

**Comment by Gobluebro** [comment]
> http://zkjellberg.github.io/dark-souls-3-cheat-sheet/#Cemetery_of_Ash

I take it you mean the "hide completed" button
![image](https://user-images.githubusercontent.com/14102413/160471378-36771f21-d4ec-4178-a9bb-25a070d757ef.png)

Yeah okay I think this is doable since the button acts as a toggle.

Though I want to preface this as, this website is not supposed to be the same as this website. I'm not going to be making a game guide like this website does where it tells you where to go in your play through to collect everything. 

If anyone was looking for that in this website, you should fork this repo or [ZKjellberg's repo](https://github.com/ZKjellberg/dark-souls-3-cheat-sheet) and create it yourself.

**Comment by Gobluebro** [comment]
Added this feature [in this commit](https://github.com/Gobluebro/Elden-Ring-Checklist/commit/f958dfb2394c6e78e1955e9abf229c5fd5d5e2f7)

**Comment by kingkhezu** [comment]
Wow you guys are fast, thx for the fast implementation.
And TBH i think the info you provide is already enough, I just wanted the list of graces & bosses to be a bit more organized.
Thank you sincerely, guess I'll be hunting down some more graces then :P
