### ISSUE TITLE
No Volcano Manor bosses?

### ISSUE THREAD

**Issue by JustAnOkapi** [Gobluebro/Elden-Ring-Checklist#8]
for example the godskin noble 
[Volcano Manor](https://eldenring.wiki.fextralife.com/Volcano+Manor): Located at the Temple of Eiglay (grants the Trophy / Achievement "Godskin Noble"). This temple is visible from the Prison Town Church grace, but the bridge leading to it is lowered to begin with. Instead, from the Prison Town Church grace you must trace a path around the edge of the lava lake westward over the rooftops and then south, until you can drop down to the lava lake's surface. Cross to the southern side of the lake from the west side and climb up to the area with many cages. One of the cages is an elevator. Climb up the steps after the elevator to reach the Temple of Eiglay.

**Comment by JustAnOkapi** [comment]
it has these bosses:
BOSSES
[Abductor Virgins](https://eldenring.wiki.fextralife.com/Abductor+Virgins)
[Godskin Noble](https://eldenring.wiki.fextralife.com/Godskin+Noble)
[God-Devouring Serpent](https://eldenring.wiki.fextralife.com/God-Devouring+Serpent)
[Magma Wyrm](https://eldenring.wiki.fextralife.com/Magma+Wyrm)
[Rykard, Lord of Blasphemy](https://eldenring.wiki.fextralife.com/Rykard,+Lord+of+Blasphemy)

**Comment by Gobluebro** [comment]
Volcano Manor bosses are listed under Mt. Gelmir since they are a subregion of Mt. Gelmir.

Most of these bosses come from this page https://eldenring.wiki.fextralife.com/Bosses though it's still a work in progress.

**Comment by Gobluebro** [comment]
It's not the most perfect solution since you could say well Mt. Gelmir is a sub region of Altus Plateau. See https://eldenring.wiki.fextralife.com/Maps

Then that would mean why is Weeping Peninsula under Limgrave then. Well there really isn't a good answer besides this is just how I found the data organized in the first place. I don't really have an idea yet on how I want them organized but for now I'm mostly concerned with just making sure I have all bosses listed.

**Comment by 13xforever** [comment]
Just wanted to point out that [Astel, Naturalborn of the Void](https://eldenring.wiki.fextralife.com/Astel+Naturalborn+of+the+Void) grace is under the Ainsel River Main section (both in game and in checklist), but the boss is listed under the Lake of Rot (probably because you get to it through that area). It should probably be consistent and moved to the Ainsel River.

**Comment by 13xforever** [comment]
Related, [Fell Twins](https://eldenring.wiki.fextralife.com/Fell+Twins) are technically in the Forbidden Lands, as you're in that territory (still covered during the first playthrough, and near the Divine Tower of East Altus, which is also listed in the Forbidden Lands in game and in checklist)

**Comment by Gobluebro** [comment]
Hey y'all sorry to bring up this old thread. In the end I am just going to default to what the bosses page says. That seems to be the easiest solution.
