### ISSUE TITLE
Add Missing Items

### ISSUE THREAD

**Issue by trevorphillipscoding** [Gobluebro/Elden-Ring-Checklist#80]
Here are pictures of the items i have in my inventory that i did not see which doing the checklist
![Screenshot 2024-07-07 193523](https://github.com/Gobluebro/Elden-Ring-Checklist/assets/43789702/429236a5-87ff-432c-ae2f-81b6611fcce5)
![Screenshot 2024-07-07 193638](https://github.com/Gobluebro/Elden-Ring-Checklist/assets/43789702/ebf372f4-911e-48fe-bf35-f112f7631a42)
![Screenshot 2024-07-07 193728](https://github.com/Gobluebro/Elden-Ring-Checklist/assets/43789702/8f70fb68-bb91-454f-a21f-22ff73898848)
![Screenshot 2024-07-07 194053](https://github.com/Gobluebro/Elden-Ring-Checklist/assets/43789702/9133b132-7967-42ef-9768-f23560289f03)

**Comment by Gobluebro** [comment]
![Screenshot 2024-07-07 193523](https://private-user-images.githubusercontent.com/43789702/346405311-429236a5-87ff-432c-ae2f-81b6611fcce5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDQzMDQsIm5iZiI6MTcyMDQwNDAwNCwicGF0aCI6Ii80Mzc4OTcwMi8zNDY0MDUzMTEtNDI5MjM2YTUtODdmZi00MzJjLWFlMmYtODFiNjYxMWZjY2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAyMDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZDM2YTgwYTk0OGJjODlmYTJjMmE3NGYyOTE0MGRkY2QxYThlODIxMzg4YjM5YzkxMDQzZjg5MDIwZjlhN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Za8LjZBh0dh1RURU4QBLZ2SL8p_h6ixHr4JNO6f-f3w)

This is in Hammers as per the hammer type labeling in the wiki.

![Screenshot 2024-07-07 193638](https://private-user-images.githubusercontent.com/43789702/346405315-ebf372f4-911e-48fe-bf35-f112f7631a42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDQzMDQsIm5iZiI6MTcyMDQwNDAwNCwicGF0aCI6Ii80Mzc4OTcwMi8zNDY0MDUzMTUtZWJmMzcyZjQtOTExZS00OGZlLWJmMzUtZjExMmY3NjMxYTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAyMDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZDMxZTcxYmE3ZGQyZGNmN2FmMzdlZGIyNjljMzdkM2IwMGI3N2JhNGY5NWJiZmU0NWMxNGUxOThlYWQ2MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ouUf9zfPhz3DUPjR4_feAkUmEfBwDpUd1579wm4RiBM) 

This is labeled as Butchering Knife because depending on the infusion of the weapon, the name changes. If you infused it with Keen it would become the Keen Butchering Knife instead. https://eldenring.wiki.fextralife.com/Butchering+Knife The weapon comes pre-infused with Sacred enhancement. 

![Screenshot 2024-07-07 193728](https://private-user-images.githubusercontent.com/43789702/346405317-8f70fb68-bb91-454f-a21f-22ff73898848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDQzMDQsIm5iZiI6MTcyMDQwNDAwNCwicGF0aCI6Ii80Mzc4OTcwMi8zNDY0MDUzMTctOGY3MGZiNjgtYmI5MS00NTRmLWEyMWYtMjJmZjczODk4ODQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAyMDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZGEwZTAxM2E3ZTAwMjVmZDBjMTM1YWM2MmUyYTJjNTg1NzliZTc3Mjc4ZmJmODcwOGZmMjE0ZmJlNGY2ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IuKwEWb-C4uPYDeLpdlD2pyO3FkqfdImtcwajuwRshs) 

Confirmed it is missing, as well as Forked-Tongue Hatchet.

![Screenshot 2024-07-07 194053](https://private-user-images.githubusercontent.com/43789702/346405320-9133b132-7967-42ef-9768-f23560289f03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDQzMDQsIm5iZiI6MTcyMDQwNDAwNCwicGF0aCI6Ii80Mzc4OTcwMi8zNDY0MDUzMjAtOTEzM2IxMzItNzk2Ny00MmVmLTk3NjgtZjIzNTYwMjg5ZjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAyMDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOTI4MDljNjU3YzNkZDZiYjM2MThhNjU3ZTI0OWY1NjNjMGY0MzJhZGE0MmVmZjMzMDY2ZmNmNzA2ZWY1OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pgmVakXSso_2sZLKnXgLAm0LirOKNEmwE-K8z5_uMn8)

This is in Greatswords 
![image](https://github.com/Gobluebro/Elden-Ring-Checklist/assets/14102413/c14b0ee3-08d2-4888-9357-2f6dc2333240)

**Comment by Gobluebro** [comment]
Added the missing axes in 36b0066

Thanks!

**Comment by Gobluebro** [comment]
I see now that freyja's greatsword is a curved greatsword. I'll move it
