### ISSUE TITLE
Deeproot Depths missing a new boss

### ISSUE THREAD

**Issue by dporem** [Gobluebro/Elden-Ring-Checklist#83]
Hi, 

Hope this time i am seeing right, but i think you are missing [Erdtree Avatar](https://eldenring.wiki.fextralife.com/Erdtree+Avatar) in [Deeproot Depths](https://eldenring.wiki.fextralife.com/Deeproot+Depths).

Thanks!

**Comment by Gobluebro** [comment]
I don't think I will add it due to it not having a named boss health bar. I do see that it does not respawn once killed but I think for consideration to be a boss you should have a boss bar.

![236690919-6ed2b655-0eb2-41f1-aa92-8a6eb3204207](https://github.com/user-attachments/assets/04086e0e-5916-4adf-a2ca-97126925074f)

**Comment by Gobluebro** [comment]
Video confirming no boss bar
https://www.youtube.com/watch?v=Um2vyWYLf6Y
